### ISSUE TITLE
No GUI disabled

### ISSUE THREAD

**Issue by Chenelusive** [moler-group/pyrpl-squid#1]
hello, i would like to know is there anyway to make the GUI available when running relock function?

**Comment by loganbvh** [comment]
Yes, that's a good idea. Please try the changes on this branch and let me know how it works for you: https://github.com/moler-group/pyrpl-squid/pull/2/files

**Comment by loganbvh** [comment]
The only important change is to call `pyqt.QtWidgets.QApplication.instance().processEvents()` in each iteration of the loop. This allows the GUI event loop time to update the GUI's state.

**Comment by Chenelusive** [comment]
> 

thanks, it works.however, the curve in scope still stop when running script,is there anyway to solve this problem?coz what I really need is the curve.

**Comment by loganbvh** [comment]
Are you saying that the trace in the GUI is being updated while the script is running, but when you click "save_curve" you don't get the current data?

**Comment by loganbvh** [comment]
https://github.com/moler-group/pyrpl-squid/pull/2

**Comment by Chenelusive** [comment]
> Are you saying that the trace in the GUI is being updated while the script is running, but when you click "save_curve" you don't get the current data?

I haven't tried clicking save_curve yet, so this function can still work although the trace in GUI stopped?I mean when the trace stops,it only disables dispalying,but the save_curve can still save current curve?

**Comment by loganbvh** [comment]
I am just trying to understand the problem you are describing. You said "it works.however, the curve in scope still stop when running script" - Can you explain in more detail what you mean by that?

I think that for whatever value you set for `delay`, the scope curve on screen should "refresh" roughly at that interval. But you're saying that the scope curve does not refresh?

**Comment by Chenelusive** [comment]
> 

yes,it didn't refresh and just stopped ,sorry for not explaining more explicitly

**Comment by loganbvh** [comment]
Does the rest of the GUI work? Can you open the dropdown menus, etc., or is the whole GUI frozen?

**Comment by Chenelusive** [comment]
> Does the rest of the GUI work? Can you open the dropdown menus, etc., or is the whole GUI frozen?

The rest of GUI works and I can open the dropdown menus,everything but trace works

**Comment by loganbvh** [comment]
Could it be a problem with the scope triggering? What is your setting for `trigger_source` and what happens if you set the `trigger_source` to `immediately` and `trigger_mode` to `Normal`?
 
![image](https://user-images.githubusercontent.com/20325010/159200960-41423856-b4ea-451a-bb9e-40ae092de0fd.png)

**Comment by Chenelusive** [comment]
Thanks!you are right, it works when I  set the trigger_source to immediately

**Comment by loganbvh** [comment]
Okay great! Should I close this issue?

**Comment by Chenelusive** [comment]
Of course,thank you very much again!
